SELECT * FROM ACT_EVT_LOG ORDER BY PROC_DEF_ID_ ASC;
SELECT * FROM ACT_GE_BYTEARRAY;
SELECT * FROM ACT_GE_PROPERTY;
SELECT * FROM ACT_HI_ACTINST ORDER BY PROC_DEF_ID_ ASC;
SELECT * FROM ACT_HI_ATTACHMENT;
SELECT * FROM ACT_HI_COMMENT;
SELECT * FROM ACT_HI_DETAIL ORDER BY PROC_INST_ID_ ASC;
SELECT * FROM ACT_HI_IDENTITYLINK;
SELECT * FROM ACT_HI_PROCINST ORDER BY PROC_DEF_ID_ ASC;
SELECT * FROM ACT_HI_TASKINST ORDER BY PROC_DEF_ID_ ASC;
SELECT * FROM ACT_HI_VARINST;
SELECT * FROM ACT_ID_GROUP;
SELECT * FROM ACT_ID_INFO;
SELECT * FROM ACT_ID_MEMBERSHIP;
SELECT * FROM ACT_ID_USER;
SELECT * FROM ACT_PROCDEF_INFO;
SELECT * FROM ACT_RE_DEPLOYMENT;
SELECT * FROM ACT_RE_MODEL;
SELECT * FROM ACT_RE_PROCDEF;
SELECT * FROM ACT_RU_EVENT_SUBSCR;
SELECT * FROM ACT_RU_EXECUTION;
SELECT * FROM ACT_RU_IDENTITYLINK;
SELECT * FROM ACT_RU_JOB;
SELECT * FROM ACT_RU_TASK;
SELECT * FROM ACT_RU_VARIABLE;

SELECT * 
FROM ACT_RE_DEPLOYMENT DY 
WHERE DY.NAME_ = 'JUNITTestProcess.bpmn';
-- Selektiere alle Prozessdefinitionen für Deployment 'JUNITTestProcess.bpmn'
SELECT PD.* 
FROM ACT_RE_PROCDEF PD INNER JOIN ACT_RE_DEPLOYMENT DY ON PD.DEPLOYMENT_ID_ = DY.ID_ WHERE DY.NAME_ = 'JUNITTestProcess.bpmn'; 
-- Selektiere alle Prozessinstanzen für alle Prozessdefinitionen für Deployment 'JUNITTestProcess.bpmn'
SELECT PI.* 
FROM ACT_HI_PROCINST PI 
WHERE PI.PROC_DEF_ID_ IN ( SELECT PD.ID_ 
                           FROM ACT_RE_PROCDEF PD INNER JOIN ACT_RE_DEPLOYMENT DY ON PD.DEPLOYMENT_ID_ = DY.ID_ WHERE DY.NAME_ = 'JUNITTestProcess.bpmn'
                         );
SELECT A.* 
FROM ACT_HI_ACTINST A 
WHERE A.PROC_INST_ID_ IN ( SELECT PI.PROC_INST_ID_ 
                           FROM ACT_HI_PROCINST PI 
                           WHERE PI.PROC_DEF_ID_ IN ( SELECT PD.ID_ 
                                                      FROM ACT_RE_PROCDEF PD INNER JOIN ACT_RE_DEPLOYMENT DY ON PD.DEPLOYMENT_ID_ = DY.ID_ WHERE DY.NAME_ = 'JUNITTestProcess.bpmn'
                                                    )
                         );

SELECT AT.* 
FROM ACT_HI_ATTACHMENT AT 
WHERE AT.PROC_INST_ID_ IN ( SELECT A.PROC_INST_ID_ 
                            FROM ACT_HI_ACTINST A 
                            WHERE A.PROC_INST_ID_ IN ( SELECT PI.PROC_INST_ID_ 
                                                       FROM ACT_HI_PROCINST PI 
                                                       WHERE PI.PROC_DEF_ID_ IN ( SELECT PD.ID_ 
                                                                                  FROM ACT_RE_PROCDEF PD INNER JOIN ACT_RE_DEPLOYMENT DY ON PD.DEPLOYMENT_ID_ = DY.ID_ WHERE DY.NAME_ = 'JUNITTestProcess.bpmn'
                                                                                )
                                                     )
                          );

SELECT P.START_USER_ID_, A.* FROM ACT_HI_ACTINST A INNER JOIN ACT_HI_PROCINST P ON A.PROC_INST_ID_ = P.PROC_INST_ID_ WHERE P.START_USER_ID_ = 'cavdark';
SELECT * FROM ACT_HI_ACTINST A WHERE A.PROC_INST_ID_ IN (SELECT P.PROC_INST_ID_ FROM ACT_HI_PROCINST P WHERE P.START_USER_ID_ = 'cavdark');
DELETE FROM ACT_HI_ACTINST A WHERE A.PROC_INST_ID_ IN (SELECT P.PROC_INST_ID_ FROM ACT_HI_PROCINST P WHERE P.START_USER_ID_ = 'cavdark');

SELECT P.START_USER_ID_, AT.* FROM ACT_HI_ATTACHMENT AT INNER JOIN ACT_HI_PROCINST P ON AT.PROC_INST_ID_ = P.PROC_INST_ID_ WHERE P.START_USER_ID_ = 'cavdark';
DELETE FROM ACT_HI_ATTACHMENT AT WHERE AT.PROC_INST_ID_ IN (SELECT P.PROC_INST_ID_ FROM ACT_HI_PROCINST P WHERE P.START_USER_ID_ = 'cavdark');

SELECT P.START_USER_ID_, C.* FROM ACT_HI_COMMENT C INNER JOIN ACT_HI_PROCINST P ON C.PROC_INST_ID_ = P.PROC_INST_ID_ WHERE P.START_USER_ID_ = 'cavdark';
DELETE FROM ACT_HI_COMMENT C WHERE C.PROC_INST_ID_ IN (SELECT P.PROC_INST_ID_ FROM ACT_HI_PROCINST P WHERE P.START_USER_ID_ = 'cavdark');

SELECT P.START_USER_ID_, D.* FROM ACT_HI_DETAIL D INNER JOIN ACT_HI_PROCINST P ON D.PROC_INST_ID_ = P.PROC_INST_ID_ WHERE P.START_USER_ID_ = 'cavdark';
DELETE FROM ACT_HI_DETAIL D WHERE D.PROC_INST_ID_ IN (SELECT P.PROC_INST_ID_ FROM ACT_HI_PROCINST P WHERE P.START_USER_ID_ = 'cavdark');

SELECT P.START_USER_ID_, I.* FROM ACT_HI_IDENTITYLINK I INNER JOIN ACT_HI_PROCINST P ON I.PROC_INST_ID_ = P.PROC_INST_ID_ WHERE P.START_USER_ID_ = 'cavdark';
DELETE FROM ACT_HI_IDENTITYLINK I WHERE I.PROC_INST_ID_ IN (SELECT P.PROC_INST_ID_ FROM ACT_HI_PROCINST P WHERE P.START_USER_ID_ = 'cavdark');

SELECT P.START_USER_ID_, T.* FROM ACT_HI_TASKINST T INNER JOIN ACT_HI_PROCINST P ON T.PROC_INST_ID_ = P.PROC_INST_ID_ WHERE P.START_USER_ID_ = 'cavdark';
DELETE FROM ACT_HI_TASKINST T WHERE T.PROC_INST_ID_ IN (SELECT P.PROC_INST_ID_ FROM ACT_HI_PROCINST P WHERE P.START_USER_ID_ = 'cavdark');

SELECT P.START_USER_ID_, V.* FROM ACT_HI_VARINST V INNER JOIN ACT_HI_PROCINST P ON V.PROC_INST_ID_ = P.PROC_INST_ID_ WHERE P.START_USER_ID_ = 'cavdark';
DELETE FROM ACT_HI_VARINST V WHERE V.PROC_INST_ID_ IN (SELECT P.PROC_INST_ID_ FROM ACT_HI_PROCINST P WHERE P.START_USER_ID_ = 'cavdark');

SELECT P.START_USER_ID_, RT.* FROM ACT_RU_TASK RT INNER JOIN ACT_HI_PROCINST P ON RT.PROC_INST_ID_ = P.PROC_INST_ID_ WHERE P.START_USER_ID_ = 'cavdark';
DELETE FROM ACT_RU_TASK RT WHERE RT.PROC_INST_ID_ IN (SELECT P.PROC_INST_ID_ FROM ACT_HI_PROCINST P WHERE P.START_USER_ID_ = 'cavdark');

SELECT P.START_USER_ID_, RV.* FROM ACT_RU_VARIABLE RV INNER JOIN ACT_HI_PROCINST P ON RV.PROC_INST_ID_ = P.PROC_INST_ID_ WHERE P.START_USER_ID_ = 'cavdark';
DELETE FROM ACT_RU_VARIABLE RV WHERE RV.PROC_INST_ID_ IN (SELECT P.PROC_INST_ID_ FROM ACT_HI_PROCINST P WHERE P.START_USER_ID_ = 'cavdark');

SELECT P.START_USER_ID_, IDL.* FROM ACT_RU_IDENTITYLINK IDL INNER JOIN ACT_HI_PROCINST P ON IDL.PROC_INST_ID_ = P.PROC_INST_ID_ WHERE P.START_USER_ID_ = 'cavdark';
DELETE FROM ACT_RU_IDENTITYLINK IDL WHERE IDL.PROC_INST_ID_ IN (SELECT P.PROC_INST_ID_ FROM ACT_HI_PROCINST P WHERE P.START_USER_ID_ = 'cavdark');

SELECT P.START_USER_ID_, E.* FROM ACT_RU_EXECUTION E INNER JOIN ACT_HI_PROCINST P ON E.PROC_INST_ID_ = P.PROC_INST_ID_ WHERE P.START_USER_ID_ = 'cavdark';
DELETE FROM ACT_RU_EXECUTION E WHERE E.PROC_INST_ID_ IN (SELECT P.PROC_INST_ID_ FROM ACT_HI_PROCINST P WHERE P.START_USER_ID_ = 'cavdark');

DELETE FROM ACT_HI_PROCINST WHERE START_USER_ID_ = 'cavdark';
DELETE FROM ACT_HI_PROCINST WHERE START_USER_ID_ = 'cavdark';

ROLLBACK;
COMMIT;