ENE-BDR\ Beteiligten-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-BDR\ Beteiligten-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\BDR
ENE-BDR\ Beteiligten-Exporte.CREFO_TAGNAME = crefonummer
ENE-BDR\ Beteiligten-Exporte.INVERT_RESULTS = false
ENE-BDR\ Beteiligten-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-BDR\ Beteiligten-Exporte.RESULT_TYPE = CREFOS_COUNT
ENE-BDR\ Beteiligten-Exporte.SEARCH1 = bip_beteiligtendaten=
ENE-BDR\ Firmen-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-BDR\ Firmen-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\BDR
ENE-BDR\ Firmen-Exporte.CREFO_TAGNAME = crefonummer
ENE-BDR\ Firmen-Exporte.INVERT_RESULTS = false
ENE-BDR\ Firmen-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-BDR\ Firmen-Exporte.RESULT_TYPE = CREFOS_COUNT
ENE-BDR\ Firmen-Exporte.SEARCH1 = bip_stammdaten=
ENE-BDR\ Löschsätze.XML_STREAM_PROCESSOR = LINEAR
ENE-BDR\ Löschsätze.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\BDR
ENE-BDR\ Löschsätze.CREFO_TAGNAME = crefo-zur-loeschung
ENE-BDR\ Löschsätze.INVERT_RESULTS = false
ENE-BDR\ Löschsätze.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-BDR\ Löschsätze.RESULT_TYPE = CREFOS_COUNT
ENE-BDR\ Löschsätze.SEARCH1 = bip_loeschsatzexport=
