ENE-BVD\ Beteiligten-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-BVD\ Beteiligten-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\BVD
ENE-BVD\ Beteiligten-Exporte.CREFO_TAGNAME = crefonummer
ENE-BVD\ Beteiligten-Exporte.INVERT_RESULTS = false
ENE-BVD\ Beteiligten-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-BVD\ Beteiligten-Exporte.RESULT_TYPE = CREFOS_COUNT
ENE-BVD\ Beteiligten-Exporte.SEARCH1 = bvd_beteiligtenexport=
ENE-BVD\ Firmen-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-BVD\ Firmen-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\BVD
ENE-BVD\ Firmen-Exporte.CREFO_TAGNAME = crefonummer
ENE-BVD\ Firmen-Exporte.INVERT_RESULTS = false
ENE-BVD\ Firmen-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-BVD\ Firmen-Exporte.RESULT_TYPE = CREFOS_COUNT
ENE-BVD\ Firmen-Exporte.SEARCH1 = bvd_firmendatenexport=
ENE-BVD\ Löschsätze.XML_STREAM_PROCESSOR = LINEAR
ENE-BVD\ Löschsätze.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\BVD
ENE-BVD\ Löschsätze.CREFO_TAGNAME = bvd-crefonummer
ENE-BVD\ Löschsätze.INVERT_RESULTS = false
ENE-BVD\ Löschsätze.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-BVD\ Löschsätze.RESULT_TYPE = CREFOS_COUNT
ENE-BVD\ Löschsätze.SEARCH1 = bvd_loeschsatzexport=
