ENE-CTC\ Löschsätze.XML_STREAM_PROCESSOR = LINEAR
ENE-CTC\ Löschsätze.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\CTC
ENE-CTC\ Löschsätze.CREFO_TAGNAME = delete
ENE-CTC\ Löschsätze.INVERT_RESULTS = false
ENE-CTC\ Löschsätze.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-CTC\ Löschsätze.RESULT_TYPE = CREFOS_COUNT
ENE-CTC\ Löschsätze.SEARCH1 = vve-datensatzliste=
ENE-CTC\ PrivatPerson-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-CTC\ PrivatPerson-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\CTC
ENE-CTC\ PrivatPerson-Exporte.CREFO_TAGNAME = crefonummer
ENE-CTC\ PrivatPerson-Exporte.INVERT_RESULTS = false
ENE-CTC\ PrivatPerson-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-CTC\ PrivatPerson-Exporte.RESULT_TYPE = CREFOS_COUNT
ENE-CTC\ PrivatPerson-Exporte.SEARCH1 = vve-datensatzliste=
