ENE-IKA\ PrivatPerson-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-IKA\ PrivatPerson-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\IKA
ENE-IKA\ PrivatPerson-Exporte.CREFO_TAGNAME = Crefonummer
ENE-IKA\ PrivatPerson-Exporte.INVERT_RESULTS = false
ENE-IKA\ PrivatPerson-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-IKA\ PrivatPerson-Exporte.RESULT_TYPE = CREFOS_COUNT
ENE-IKA\ PrivatPerson-Exporte.SEARCH1 = Person=
ENE-IKA\ Firmen-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-IKA\ Firmen-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\IKA
ENE-IKA\ Firmen-Exporte.CREFO_TAGNAME = Crefonummer
ENE-IKA\ Firmen-Exporte.INVERT_RESULTS = false
ENE-IKA\ Firmen-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-IKA\ Firmen-Exporte.RESULT_TYPE = CREFOS_COUNT
ENE-IKA\ Firmen-Exporte.SEARCH1 = Firma=
ENE-IKA\ Fehlersätze.XML_STREAM_PROCESSOR = LINEAR
ENE-IKA\ Fehlersätze.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\IKA
ENE-IKA\ Fehlersätze.CREFO_TAGNAME = Crefonummer
ENE-IKA\ Fehlersätze.INVERT_RESULTS = false
ENE-IKA\ Fehlersätze.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-IKA\ Fehlersätze.RESULT_TYPE = CREFOS_COUNT
ENE-IKA\ Fehlersätze.SEARCH1 = fehlerBeauftragteCrefo=
