ENE-VSH\ Beteiligten-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-VSH\ Beteiligten-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\VSH
ENE-VSH\ Beteiligten-Exporte.CREFO_TAGNAME = crefonummer
ENE-VSH\ Beteiligten-Exporte.INVERT_RESULTS = false
ENE-VSH\ Beteiligten-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-VSH\ Beteiligten-Exporte.RESULT_TYPE = CREFOS_COUNT
ENE-VSH\ Beteiligten-Exporte.SEARCH1 = vsh_beteiligtenexport=
ENE-VSH\ Firmen-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-VSH\ Firmen-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\VSH
ENE-VSH\ Firmen-Exporte.CREFO_TAGNAME = crefonummer
ENE-VSH\ Firmen-Exporte.INVERT_RESULTS = false
ENE-VSH\ Firmen-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-VSH\ Firmen-Exporte.RESULT_TYPE = CREFOS_COUNT
ENE-VSH\ Firmen-Exporte.SEARCH1 = vsh_firmendatenexport=
ENE-VSH\ Löschsätze.XML_STREAM_PROCESSOR = LINEAR
ENE-VSH\ Löschsätze.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\VSH
ENE-VSH\ Löschsätze.CREFO_TAGNAME = vsh-crefonummer
ENE-VSH\ Löschsätze.INVERT_RESULTS = false
ENE-VSH\ Löschsätze.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-VSH\ Löschsätze.RESULT_TYPE = CREFOS_COUNT
ENE-VSH\ Löschsätze.SEARCH1 = vsh_loeschsatzexport=
