ENE-ZEW\ Beteiligten-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-ZEW\ Beteiligten-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\ZEW
ENE-ZEW\ Beteiligten-Exporte.CREFO_TAGNAME = crefonummer
ENE-ZEW\ Beteiligten-Exporte.INVERT_RESULTS = false
ENE-ZEW\ Beteiligten-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-ZEW\ Beteiligten-Exporte.RESULT_TYPE = CREFOS_COUNT
ENE-ZEW\ Beteiligten-Exporte.SEARCH1 = zew-beteiligten-export=
ENE-ZEW\ Firmen-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-ZEW\ Firmen-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\ZEW
ENE-ZEW\ Firmen-Exporte.CREFO_TAGNAME = crefonummer
ENE-ZEW\ Firmen-Exporte.INVERT_RESULTS = false
ENE-ZEW\ Firmen-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-ZEW\ Firmen-Exporte.RESULT_TYPE = CREFOS_COUNT
ENE-ZEW\ Firmen-Exporte.SEARCH1 = zew-firmen-export=
ENE-ZEW\ Löschsätze.XML_STREAM_PROCESSOR = LINEAR
ENE-ZEW\ Löschsätze.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\ZEW
ENE-ZEW\ Löschsätze.CREFO_TAGNAME = crefonummer
ENE-ZEW\ Löschsätze.INVERT_RESULTS = false
ENE-ZEW\ Löschsätze.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-ZEW\ Löschsätze.RESULT_TYPE = CREFOS_COUNT
ENE-ZEW\ Löschsätze.SEARCH1 = zew-loeschsatz-export=
