DEFAULT.XML_STREAM_PROCESSOR=LINEAR
DEFAULT.RESULTS_PATH=./GEE/SearchResults
# CREFOS_COUNT | CREFOS_LIST | CREFOS_XML
DEFAULT.RESULT_TYPE=CREFOS_XML

GEE_RTN_FULL_2014-10-22_09-51.SOURCE=//fileserver.gee.creditreform.de/gee/rtn/export/full/2014-10-22_09-51
GEE_RTN_FULL_2014-10-22_09-51.CREFO_TAGNAME=crefonummer
GEE_RTN_FULL_2014-10-22_09-51.SEARCH=anzahl-nachtragspflichtige-auftraege=[0-9]+

GEE_BDR_DELTA_2014-10-13_07-00.SOURCE=//fileserver.gee.creditreform.de/gee/bedirect/export/delta/2014-10-13_07-00 
GEE_BDR_DELTA_2014-10-13_07-00.CREFO_TAGNAME=crefonummer
GEE_BDR_DELTA_2014-10-13_07-00.SEARCH1=strasse="Schlagbaumer Str."
GEE_BDR_DELTA_2014-10-13_07-00.SEARCH2=firmierung-alt="Wilken GmbH u Co. KG"
GEE_BDR_DELTA_2014-10-13_07-00.SEARCH3=anzahl-auskuenfte=20[0..9]{1}

GEE_BVD_DELTA_2014-08-11_10-54.SOURCE=//fileserver.gee.creditreform.de/gee/bvd/export/delta/2014-08-11_10-54
GEE_BVD_DELTA_2014-08-11_10-54.CREFO_TAGNAME=crefonummer
GEE_BVD_DELTA_2014-08-11_10-54.SEARCH1=branchencode=46153
GEE_BVD_DELTA_2014-08-11_10-54.SEARCH2=strasse=Langegasse
GEE_BVD_DELTA_2014-08-11_10-54.SEARCH3=branchenart=ÖNACE.*

GEE_CEF_DELTA_2014-10-14_07-00.SOURCE=//fileserver.gee.creditreform.de/gee/cef/export/delta/2014-10-14_07-00
GEE_CEF_DELTA_2014-10-14_07-00.CREFO_TAGNAME=crefo-number
GEE_CEF_DELTA_2014-10-14_07-00.SEARCH1=designation=HRA
GEE_CEF_DELTA_2014-10-14_07-00.SEARCH2=postcode=99[0..9]{3}

GEE_CTC_DELTA_2014-10-14_13-00.SOURCE=//fileserver.gee.creditreform.de/gee/ctc/export/delta/2014-10-14_13-00
GEE_CTC_DELTA_2014-10-14_13-00.CREFO_TAGNAME=crefonummer
GEE_CTC_DELTA_2014-10-14_13-00.SEARCH1=aktennummer=1005009[0..9]{2}
GEE_CTC_DELTA_2014-10-14_13-00.SEARCH2=abgeschlossen=true
GEE_CTC_DELTA_2014-10-14_13-00.SEARCH3=betrag=5[0..9]{3}

GEE_DRD_DELTA_2014-10-01_15-18.SOURCE=//fileserver.gee.creditreform.de/gee/drd/export/delta/2014-10-01_15-18
GEE_DRD_DELTA_2014-10-01_15-18.CREFO_TAGNAME=crefonummer
GEE_DRD_DELTA_2014-10-01_15-18.SEARCH1=rechtsformInhabergefuehrt=false
GEE_DRD_DELTA_2014-10-01_15-18.SEARCH2=rechtsformID=102[0..9]{2}

GEE_FW_DELTA_2014-10-14_07-00.SOURCE=//fileserver.gee.creditreform.de/gee/fw/export/delta/2014-10-14_07-00 
GEE_FW_DELTA_2014-10-14_07-00.CREFO_TAGNAME=crefonummer
GEE_FW_DELTA_2014-10-14_07-00.SEARCH1=name1="Wilken Nachtragscrefo"
GEE_FW_DELTA_2014-10-14_07-00.SEARCH2=registerart=HRA

GEE_RTN_FULL_2014-10-01_08-55.SOURCE=//fileserver.gee.creditreform.de/gee/rtn/export/full/2014-10-01_08-55
GEE_RTN_FULL_2014-10-01_08-55.CREFO_TAGNAME=crefonummer
GEE_RTN_FULL_2014-10-01_08-55.SEARCH1=schluessel-alte-welt=6
GEE_RTN_FULL_2014-10-01_08-55.SEARCH2=auskunft-abgefragt=true
GEE_RTN_FULL_2014-10-01_08-55.SEARCH3=datum-gruendung=jahr:2009
GEE_RTN_FULL_2014-10-01_08-55.SEARCH4=gesperrt=true
GEE_RTN_FULL_2014-10-01_08-55.SEARCH5=sperre-werbung=false
GEE_RTN_FULL_2014-10-01_08-55.SEARCH6=bezeichnung=Fehlbericht

GEE_VSH_2014-10-01_07-00.SOURCE=//fileserver.gee.creditreform.de/gee/vsh/export/delta/2014-10-01_07-00
GEE_VSH_2014-10-01_07-00.CREFO_TAGNAME=crefonummer
GEE_VSH_2014-10-01_07-00.SEARCH1=letzte-aenderung=2014-09-23.*
GEE_VSH_2014-10-01_07-00.SEARCH2=anzahl-auskuenfte=[1..9]
GEE_VSH_2014-10-01_07-00.SEARCH3=bonitaets-index=297
GEE_VSH_2014-10-01_07-00.SEARCH4=crefonummer-beteiligter=2192001679
