[DEFAULT]
  XML_STREAM_PROCESSOR=LINEAR
  RESULTS_PATH=./LOC/SearchResults
  # CREFOS_COUNT | CREFOS_LIST | CREFOS_XML
  RESULT_TYPE=CREFOS_XML

[TST_BVD_DELTA_2014-05-06_07-00]
SOURCE=./ENE/ExportedXMLsDir/bvd/export/delta/2014-05-06_07-00
CREFO_TAGNAME=crefonummer
SEARCH1=vorname=Bert
SEARCH2=strasse=Altenburgstr
SEARCH3=beteiligt-seit=jahr:201[0-9]{1}
SEARCH4=branchencode=43220

[TST_CEF_DELTA_2014-05-06_07-14]
SOURCE=./ENE/ExportedXMLsDir/cef/export/delta/2014-05-06_07-14
CREFO_TAGNAME=crefo-number
SEARCH1=register-id=101332
SEARCH2=legal-form.key=LEFO-DE-3
SEARCH3=company-facilities.legal-office.mailing-address.address-for-service.city=Einbeck
SEARCH4=register-court.city=Braunschweig
SEARCH5=company-status.designation=erloschen

[TST_TC_DELTA_2014-05-07_13-00]
SOURCE=./ENE/ExportedXMLsDir/ctc/export/delta/2014-05-07_13-00
CREFO_TAGNAME=crefonummer
SEARCH1=datumRecherche>2014-05-*
