[DEFAULT]
  XML_STREAM_PROCESSOR=LINEAR
  RESULTS_PATH=./PRE/SearchResults
  # CREFOS_COUNT | CREFOS_LIST | CREFOS_XML
  RESULT_TYPE=CREFOS_XML

[PRE_BDR_DELTA_2014-10-06_07-00]
SOURCE=//fileserver.pre.creditreform.de/pre/bedirect/export/delta/2014-10-06_07-00
CREFO_TAGNAME=crefonummer
SEARCH1=vorname=Thomas
SEARCH2=gewerbetaetigkeit=Schankwirtschaft
SEARCH3=beteiligt-seit=jahr:2009
SEARCH4=registernummer=1003[0..9]{2}

[PRE_BVD_DELTA_2014-10-06_09-04]
SOURCE=//fileserver.pre.creditreform.de/pre/bvd/export/delta/2014-10-06_09-04
CREFO_TAGNAME=crefonummer
SEARCH1=branchencode=4520[0..9]
SEARCH2=bezeichnung-rechtsform=Gewerbebetrieb

[PRE_CEF_DELTA_2014-10-13_07-00]
SOURCE=//fileserver.pre.creditreform.de/pre/cef/export/delta/2014-10-13_07-00
CREFO_TAGNAME=crefo-number
SEARCH1=house-number=2[4..9]
SEARCH2=street=Saarbr�ckener.* 

[PRE_CTC_DELTA_2014-10-12_17-00]
SOURCE=//fileserver.pre.creditreform.de/pre/ctc/export/delta/2014-10-12_17-00
CREFO_TAGNAME=crefonummer
SEARCH1=anzahlTelefonauskuenfte=[2..9]
SEARCH2=adressbereich=0[6..9]

[PRE_DRD_DELTA_2014-10-13_03-00]
SOURCE=//fileserver.pre.creditreform.de/pre/drd/export/delta/2014-10-13_03-00
CREFO_TAGNAME=crefonummer
SEARCH1=rechtsformKurzname=Gewerbebetrieb
SEARCH2=rechtsformKurzname=OHG

[PRE_VSD_DELTA_2014-10-14_07-00]
SOURCE=//fileserver.pre.creditreform.de/pre/vsd/export/delta/2014-10-14_07-00
CREFO_TAGNAME=crefonummer
SEARCH1=beteiligteneigenschaft=Inhaber
SEARCH2=bezeichnung-erste-rechtsform=Gewerbebetrieb
