package de.creditreform.crefoteam.cte.tesun;

import org.apache.log4j.Level;

public interface TesunClientJobListener {
    String UT_TASK_PARAM_NAME_ENVIRONMENT = "ENV";
    String UT_TASK_PARAM_NAME_DEMO_MODE = "DEMO_MODE";
    String UT_TASK_PARAM_NAME_MANUEL_USER_TASK = "MANUEL_USER_TASK";

    String UT_TASK_PARAM_NAME_MEIN_KEY = "MEIN_KEY";
    String UT_TASK_PARAM_NAME_ACTIVITI_PROCESS_NAME = "ACTIVITI_PROCESS_NAME";
    String UT_TASK_PARAM_NAME_TEST_TYPE = "TEST_TYPE";
    String UT_TASK_PARAM_NAME_TEST_PHASE = "TEST_PHASE";
    String UT_TASK_PARAM_NAME_TIME_BEFORE_CT_IMPORT = "TIME_BEFORE_CT_IMPORT";
    String UT_TASK_PARAM_NAME_TIME_BEFORE_BTLG_IMPORT = "TIME_BEFORE_BTLG_IMPORT";
    String UT_TASK_PARAM_NAME_TIME_BEFORE_EXPORT = "TIME_BEFORE_EXPORT";
    String UT_TASK_PARAM_NAME_TIME_BEFORE_EXPORTS_COLLECT = "TIME_BEFORE_EXPORTS_COLLECT";
    String UT_TASK_PARAM_NAME_TIME_BEFORE_SFTP_COLLECT = "TIME_BEFORE_SFTP_COLLECT";

    String UT_TASK_PARAM_NAME_EMAIL_FROM = "EMAIL_FROM";
    String UT_TASK_PARAM_NAME_SUCCESS_EMAIL_TO = "SUCCESS_MAIL_TO";
    String UT_TASK_PARAM_NAME_FAILURE_EMAIL_TO = "FAILURE_MAIL_TO";
    String UT_TASK_PARAM_NAME_ACTIVE_CUSTOMERS = "ACTIVE_CUSTOMERS";
    String UT_TASK_PARAM_USE_ONLY_TEST_CLZ = "USE_ONLY_TEST_CLZ";
    String UT_TASK_PARAM_UPLOAD_SYNTH_TEST_CREFOS = "UPLOAD_SYNTH_TEST_CREFOS";
    String UT_TASK_PARAM_NAME_UPLOAD_EMPTY_PAYLOAD = "UPLOAD_EMPTY_PAYLOAD";

    enum ASK_FOR {
        ASK_OBJECT_CTE_VERSION,
        ASK_OBJECT_ENVIRONMENT,
        ASK_OBJECT_TEST_TYPE,
        ASK_OBJECT_USE_ITSQ_TEST_RESOURCES,
        ASK_OBJECT_ACTIVE_CUSTOMERS,
        ASK_OBJECT_EMAIL_FROM,
        ASK_OBJECT_SUCCESS_EMAIL_TO,
        ASK_OBJECT_FAILURE_EMAIL_TO,
        ASK_OBJECT_TIME_FOR_STAGING,
        ASK_OBJECT_TIME_FOR_IMPORTCYCLE,
        ASK_TEST_CASES_PATH,
        ASK_NEW_TEST_CASES_PATH,
        ASK_REF_EXPORTS_PATH,
        ASK_REF_AB30_DOCS_PATH,
        ASK_WAIT_FOR_TEST_SYSTEM,
        ASK_CHECK_COLLECTS,
        ASK_OBJECT_ANAYLSE_CHECKS,
        ASK_OBJECT_CREATE_NEW_SOLL,
        ASK_SELECTED_TEST_CUSTOMERS,
        ASK_SELECTED_TEST_CUSTOMERNAMES,
        ASK_OBJECT_NEW_SOLL_PATH,
        ASK_OBJECT_COPY_EXPORTS_TO_INPUTS,
        ASK_OBJECT_CHECK_DOWNLOADS,
        ASK_OBJECT_RETRY,
        ASK_OBJECT_CONTINUE,
        ASK_OBJECT_EXCEPTION,
    }

    void notifyClientJob(Level level, Object notifyObject);

    Object askClientJob(ASK_FOR askFor, Object userObject);

}
