#
# Created by JFormDesigner on Sat Mar 28 13:48:21 CET 2026
#

TestSupportMainControlsPanel.buttonManageJVMs.actionCommand=UT-Thread starten...
TestSupportMainControlsPanel.buttonManageJVMs.text=JVM's...
TestSupportMainControlsPanel.buttonManageJVMs.toolTipText=BPMN's aktualisieren
TestSupportMainControlsPanel.buttonRefreshEnvironment.actionCommand=UT-Thread starten...
TestSupportMainControlsPanel.buttonRefreshEnvironment.text=Aktualisieren
TestSupportMainControlsPanel.buttonRefreshEnvironment.toolTipText=UT-Thread starten...
TestSupportMainControlsPanel.labelActivitiHost.text=Activiti-Host\:
TestSupportMainControlsPanel.labelImpCycleHost.text=ImportCycle-Host\:
TestSupportMainControlsPanel.labelInsoBackEndHost.text=INSO-Backend-Host\:
TestSupportMainControlsPanel.labelInsoHost.text=INSO-Host\:
TestSupportMainControlsPanel.labelRestServicesHost.text=RestServices-Host\:
TestSupportMainControlsPanel.labelBatchGUIHost.text=Batch-GUI-Host\:
TestSupportMainControlsPanel.labelEnvironment.text=Umgebung\:
