#
# Created by JFormDesigner on Sat Mar 28 13:48:21 CET 2026
#

TestSupportMainControlsPanel.buttonManageJVMs.actionCommand=UT-Thread starten...
TestSupportMainControlsPanel.buttonManageJVMs.text=JVM's...
TestSupportMainControlsPanel.buttonManageJVMs.toolTipText=BPMN's aktualisieren
TestSupportMainControlsPanel.buttonRefreshEnvironment.actionCommand=UT-Thread starten...
TestSupportMainControlsPanel.buttonRefreshEnvironment.text=Aktualisieren
TestSupportMainControlsPanel.buttonRefreshEnvironment.toolTipText=UT-Thread starten...
TestSupportMainControlsPanel.labelActivitiHost.text=Activiti-Host\:
TestSupportMainControlsPanel.labelImpCycleHost.text=ImportCycle-Host\:
TestSupportMainControlsPanel.labelInsoBackEndHost.text=INSO-Backend-Host\:
TestSupportMainControlsPanel.labelInsoHost.text=INSO-Host\:
TestSupportMainControlsPanel.labelRestServicesHost.text=RestServices-Host\:
TestSupportMainControlsPanel.labelBatchGUIHost.text=Batch-GUI-Host\:
TestSupportMainControlsPanel.labelEnvironment.text=Umgebung\:
TestSupportMainProcessPanel.labelTestTestSource.text=Test-Source\:
TestSupportMainProcessPanel.labelITSQRevision.text=Branch\:
TestSupportMainProcessPanel.checkBoxDemoMode.text=Demo
TestSupportMainProcessPanel.checkBoxUploadSynthetics.text=Synthetische Tests hochladen
TestSupportMainProcessPanel.checkBoxUseOnlyTestCLZs.text=Nur Test-CLZs in VC-Liste
TestSupportMainProcessPanel.buttonStartProcess.text=Prozess starten...
TestSupportMainProcessPanel.buttonStartTestJob.text=JOB starten...
TestSupportMainProcessPanel.buttonStopUserTasksThread.actionCommand=UT-Thread starten...
TestSupportMainProcessPanel.buttonStopUserTasksThread.toolTipText=UT-Thread starten...
TestSupportMainProcessPanel.labelTestCasesPath.text=Testfälle\:
TestSupportMainProcessPanel.labelFachwertConfig.text=FW-Konfiguration\:
TestSupportMainProcessPanel.radioButtonFWConfigLikePRE.text=PRE
TestSupportMainProcessPanel.radioButtonExportFormatLikePRE.text=PRE
TestSupportMainProcessPanel.radioButtonExportFormatNewest.text=Neu
TestSupportMainProcessPanel.radioButtonFWConfigNewest.text=Neu
TestSupportMainProcessPanel.labelExportFormat.text=Export-Format\:
TestSupportMainProcessPanel.labelTestJobs.text=Test-Jobs\:
TestSupportMainProcessPanel.labelTestPhase.text=Test-Phase\:
TestSupportMainProcessPanel.labelJobParams.text=Job-Params\:
TestSupportMainProcessPanel.labelTestType3.text=Test-Typ\:
TestSupportMainTabPabel.checkBoxScrollToEnd.text=Auto-Scroll
TestSupportMainTabPabel.buttonClearLOGPanel.actionCommand=LOG-Panel leeren
TestSupportMainTabPabel.buttonClearLOGPanel.text=LOG-Panel leeren
TestSupportMainTabPabel.scrollPanelProcessImage.tab.title=Prozess-Image
TestSupportMainTabPabel.viewTestResults.tab.title=Test-Results
TestSupportMainTabPabel.buttonClearLOGPanel.toolTipText=LOG-Panel leeren
TestSupportMainTabPabel.panelLogs.tab.title=Logs
