#
# Created by JFormDesigner on Tue Mar 31 17:17:32 CEST 2026
#

TestSupportMainTabPabel.scrollPanelProcessImage.tab.title=Prozess
TestSupportMainTabPabel.panelLogs.tab.title=LOG's
TestSupportMainTabPabel.buttonACTITIExporer.tab.title=ACTITI-Exporer
TestSupportMainTabPabel.buttonACTITIExporer.text=text
TestSupportMainTabPabel.viewTestResults.tab.title=Test-Results
