ENE-DRD\ Firmen-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-DRD\ Firmen-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\DRD
ENE-DRD\ Firmen-Exporte.CREFO_TAGNAME = crefonummer
ENE-DRD\ Firmen-Exporte.INVERT_RESULTS = false
ENE-DRD\ Firmen-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-DRD\ Firmen-Exporte.RESULT_TYPE = CREFOS_XML
ENE-DRD\ Firmen-Exporte.SEARCH1 = drd-datensatzliste=
ENE-DRD\ Löschsätze.XML_STREAM_PROCESSOR = LINEAR
ENE-DRD\ Löschsätze.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\DRD
ENE-DRD\ Löschsätze.CREFO_TAGNAME = delete
ENE-DRD\ Löschsätze.INVERT_RESULTS = false
ENE-DRD\ Löschsätze.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-DRD\ Löschsätze.RESULT_TYPE = CREFOS_XML
ENE-DRD\ Löschsätze.SEARCH1 = drd-datensatzliste=
