ENE-FSU\ Firmen-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-FSU\ Firmen-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\FSU
ENE-FSU\ Firmen-Exporte.CREFO_TAGNAME = crefonummer
ENE-FSU\ Firmen-Exporte.INVERT_RESULTS = false
ENE-FSU\ Firmen-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-FSU\ Firmen-Exporte.RESULT_TYPE = CREFOS_XML
ENE-FSU\ Firmen-Exporte.SEARCH1 = fsu-firmendatenexport=
ENE-FSU\ Löschsätze.XML_STREAM_PROCESSOR = LINEAR
ENE-FSU\ Löschsätze.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\FSU
ENE-FSU\ Löschsätze.CREFO_TAGNAME = fsu-crefonummer
ENE-FSU\ Löschsätze.INVERT_RESULTS = false
ENE-FSU\ Löschsätze.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-FSU\ Löschsätze.RESULT_TYPE = CREFOS_XML
ENE-FSU\ Löschsätze.SEARCH1 = fsu-loeschsatzexport=
