ENE-FVD\ Beteiligten-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-FVD\ Beteiligten-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\FVD
ENE-FVD\ Beteiligten-Exporte.CREFO_TAGNAME = crefonummer
ENE-FVD\ Beteiligten-Exporte.INVERT_RESULTS = false
ENE-FVD\ Beteiligten-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-FVD\ Beteiligten-Exporte.RESULT_TYPE = CREFOS_XML
ENE-FVD\ Beteiligten-Exporte.SEARCH1 = fw-beteiligtenexport=
ENE-FVD\ Firmen-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-FVD\ Firmen-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\FVD
ENE-FVD\ Firmen-Exporte.CREFO_TAGNAME = crefonummer
ENE-FVD\ Firmen-Exporte.INVERT_RESULTS = false
ENE-FVD\ Firmen-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-FVD\ Firmen-Exporte.RESULT_TYPE = CREFOS_XML
ENE-FVD\ Firmen-Exporte.SEARCH1 = fw-firmendatenexport=
ENE-FVD\ Löschsätze.XML_STREAM_PROCESSOR = LINEAR
ENE-FVD\ Löschsätze.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\FVD
ENE-FVD\ Löschsätze.CREFO_TAGNAME = fw-crefonummer
ENE-FVD\ Löschsätze.INVERT_RESULTS = false
ENE-FVD\ Löschsätze.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-FVD\ Löschsätze.RESULT_TYPE = CREFOS_XML
ENE-FVD\ Löschsätze.SEARCH1 = fw-loeschsatzexport=
