ENE-GDL\ Firmen-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-GDL\ Firmen-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\GDL
ENE-GDL\ Firmen-Exporte.CREFO_TAGNAME = company-identifier
ENE-GDL\ Firmen-Exporte.INVERT_RESULTS = false
ENE-GDL\ Firmen-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-GDL\ Firmen-Exporte.RESULT_TYPE = CREFOS_XML
ENE-GDL\ Firmen-Exporte.SEARCH1 = update-on-capital-share=
ENE-GDL\ Löschsätze.XML_STREAM_PROCESSOR = LINEAR
ENE-GDL\ Löschsätze.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\GDL
ENE-GDL\ Löschsätze.CREFO_TAGNAME = company-identifier
ENE-GDL\ Löschsätze.INVERT_RESULTS = false
ENE-GDL\ Löschsätze.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-GDL\ Löschsätze.RESULT_TYPE = CREFOS_XML
ENE-GDL\ Löschsätze.SEARCH1 = deletion-message=
