ENE-ISM\ Firmen-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-ISM\ Firmen-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\ISM
ENE-ISM\ Firmen-Exporte.CREFO_TAGNAME = crefo-number
ENE-ISM\ Firmen-Exporte.INVERT_RESULTS = false
ENE-ISM\ Firmen-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-ISM\ Firmen-Exporte.RESULT_TYPE = CREFOS_XML
ENE-ISM\ Firmen-Exporte.SEARCH1 = update-on-company=
ENE-ISM\ Löschsätze.XML_STREAM_PROCESSOR = LINEAR
ENE-ISM\ Löschsätze.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\ISM
ENE-ISM\ Löschsätze.CREFO_TAGNAME = crefo-number
ENE-ISM\ Löschsätze.INVERT_RESULTS = false
ENE-ISM\ Löschsätze.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-ISM\ Löschsätze.RESULT_TYPE = CREFOS_XML
ENE-ISM\ Löschsätze.SEARCH1 = deletion-message=
