ENE-MIC\ Beteiligten-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-MIC\ Beteiligten-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\MIC
ENE-MIC\ Beteiligten-Exporte.CREFO_TAGNAME = crefonummer
ENE-MIC\ Beteiligten-Exporte.INVERT_RESULTS = false
ENE-MIC\ Beteiligten-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-MIC\ Beteiligten-Exporte.RESULT_TYPE = CREFOS_XML
ENE-MIC\ Beteiligten-Exporte.SEARCH1 = mic-beteiligten-export=
ENE-MIC\ Firmen-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-MIC\ Firmen-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\MIC
ENE-MIC\ Firmen-Exporte.CREFO_TAGNAME = crefonummer
ENE-MIC\ Firmen-Exporte.INVERT_RESULTS = false
ENE-MIC\ Firmen-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-MIC\ Firmen-Exporte.RESULT_TYPE = CREFOS_XML
ENE-MIC\ Firmen-Exporte.SEARCH1 = mic-firmen-export=
ENE-MIC\ Löschsätze.XML_STREAM_PROCESSOR = LINEAR
ENE-MIC\ Löschsätze.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\MIC
ENE-MIC\ Löschsätze.CREFO_TAGNAME = crefonummer
ENE-MIC\ Löschsätze.INVERT_RESULTS = false
ENE-MIC\ Löschsätze.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-MIC\ Löschsätze.RESULT_TYPE = CREFOS_XML
ENE-MIC\ Löschsätze.SEARCH1 = mic-loeschsatz-export=
