ENE-MIP\ Privatperson-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-MIP\ Privatperson-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\MIP
ENE-MIP\ Privatperson-Exporte.CREFO_TAGNAME = crefonummer
ENE-MIP\ Privatperson-Exporte.INVERT_RESULTS = false
ENE-MIP\ Privatperson-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-MIP\ Privatperson-Exporte.RESULT_TYPE = CREFOS_XML
ENE-MIP\ Privatperson-Exporte.SEARCH1 = mip-personen-export=
ENE-MIP\ Löschsätze.XML_STREAM_PROCESSOR = LINEAR
ENE-MIP\ Löschsätze.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\MIP
ENE-MIP\ Löschsätze.CREFO_TAGNAME = crefonummer
ENE-MIP\ Löschsätze.INVERT_RESULTS = false
ENE-MIP\ Löschsätze.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-MIP\ Löschsätze.RESULT_TYPE = CREFOS_XML
ENE-MIP\ Löschsätze.SEARCH1 = mip-loeschsatzexport=
