ENE-RTN\ Firmen-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-RTN\ Firmen-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\RTN
ENE-RTN\ Firmen-Exporte.CREFO_TAGNAME = crefonummer
ENE-RTN\ Firmen-Exporte.INVERT_RESULTS = false
ENE-RTN\ Firmen-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-RTN\ Firmen-Exporte.RESULT_TYPE = CREFOS_XML
ENE-RTN\ Firmen-Exporte.SEARCH1 = rtn-firmendatenexport=
ENE-RTN\ Löschsätze.XML_STREAM_PROCESSOR = LINEAR
ENE-RTN\ Löschsätze.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\RTN
ENE-RTN\ Löschsätze.CREFO_TAGNAME = crefonummer
ENE-RTN\ Löschsätze.INVERT_RESULTS = false
ENE-RTN\ Löschsätze.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-RTN\ Löschsätze.RESULT_TYPE = CREFOS_XML
ENE-RTN\ Löschsätze.SEARCH1 = rtn-loeschsatzexport=
