ENE-VSO\ Beteiligten-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-VSO\ Beteiligten-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\VSO
ENE-VSO\ Beteiligten-Exporte.CREFO_TAGNAME = crefonummer
ENE-VSO\ Beteiligten-Exporte.INVERT_RESULTS = false
ENE-VSO\ Beteiligten-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-VSO\ Beteiligten-Exporte.RESULT_TYPE = CREFOS_XML
ENE-VSO\ Beteiligten-Exporte.SEARCH1 = vsh_beteiligtenexport=
ENE-VSO\ Firmen-Exporte.XML_STREAM_PROCESSOR = LINEAR
ENE-VSO\ Firmen-Exporte.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\VSO
ENE-VSO\ Firmen-Exporte.CREFO_TAGNAME = crefonummer
ENE-VSO\ Firmen-Exporte.INVERT_RESULTS = false
ENE-VSO\ Firmen-Exporte.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-VSO\ Firmen-Exporte.RESULT_TYPE = CREFOS_XML
ENE-VSO\ Firmen-Exporte.SEARCH1 = vsh_firmendatenexport=
ENE-VSO\ Löschsätze.XML_STREAM_PROCESSOR = LINEAR
ENE-VSO\ Löschsätze.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\VSO
ENE-VSO\ Löschsätze.CREFO_TAGNAME = vsh-crefonummer
ENE-VSO\ Löschsätze.INVERT_RESULTS = false
ENE-VSO\ Löschsätze.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-VSO\ Löschsätze.RESULT_TYPE = CREFOS_XML
ENE-VSO\ Löschsätze.SEARCH1 = vsh_loeschsatzexport=
