crefo-zur-loeschung.XML_STREAM_PROCESSOR = LINEAR
crefo-zur-loeschung.SOURCE = E:\\Projekte\\Branches\\testsupport_client\\tesun_exports_searcher\\suche
crefo-zur-loeschung.CREFO_TAGNAME = crefo-zur-loeschung
crefo-zur-loeschung.LOGICAL_CONNECTION = LOGIC_OR
crefo-zur-loeschung.INVERT_RESULTS = false
crefo-zur-loeschung.RESULT_TYPE = CREFOS_XML
crefo-zur-loeschung.SEARCH1 = crefo-zur-loeschung=4123839692
crefo-zur-loeschung.SEARCH2 = crefo-zur-loeschung=4123839693
crefo-zur-loeschung.SEARCH3 = crefo-zur-loeschung=4123840050
crefo-zur-loeschung.SEARCH4 = crefo-zur-loeschung=4123840051
crefo-zur-loeschung.SEARCH5 = crefo-zur-loeschung=4123838557
crefo-zur-loeschung.SEARCH6 = crefo-zur-loeschung=4123839277
crefo-zur-loeschung.SEARCH7 = crefo-zur-loeschung=4123839280
crefo-zur-loeschung.SEARCH8 = crefo-zur-loeschung=4123839698
crefonummer.XML_STREAM_PROCESSOR = LINEAR
crefonummer.SOURCE = E:\\Projekte\\Branches\\testsupport_client\\tesun_exports_searcher\\suche
crefonummer.CREFO_TAGNAME = crefonummer
crefonummer.LOGICAL_CONNECTION = LOGIC_OR
crefonummer.INVERT_RESULTS = false
crefonummer.RESULT_TYPE = CREFOS_XML
crefonummer.SEARCH1 = crefonummer=4123839692
crefonummer.SEARCH2 = crefonummer=4123839693
crefonummer.SEARCH3 = crefonummer=4123840050
crefonummer.SEARCH4 = crefonummer=4123840051
crefonummer.SEARCH5 = crefonummer=4123838557
crefonummer.SEARCH6 = crefonummer=4123839277
crefonummer.SEARCH7 = crefonummer=4123839280
crefonummer.SEARCH8 = crefonummer=4123839698
