# 1. Konsole definieren (Das bleibt so)
log4j.appender.ConsoleAppender=org.apache.log4j.ConsoleAppender
log4j.appender.ConsoleAppender.layout=org.apache.log4j.PatternLayout
log4j.appender.ConsoleAppender.layout.ConversionPattern=%d{dd.MM.yyyy HH:mm:ss.SSS} [%-5p] %c - %m%n

# 2. Root-Logger (NUR Konsole)
log4j.rootLogger=INFO, ConsoleAppender

# Paketnamen
app.logging.package=de.creditreform.crefoteam.cte.tesun

# 3. Level für Pakete definieren (WICHTIG: Kein ", FileAppender" mehr!)
# Hier setzen wir NUR das Level. Den "Anschluss" an die Datei macht dein Java-Code.
log4j.logger.org.apache.commons.httpclient.HttpClient=INFO
log4j.logger.de.creditreform.crefoteam.cte.rest=WARN
log4j.logger.de.creditreform.crefoteam.activiti=WARN
log4j.logger.de.creditreform.crefoteam.cte.tesun=INFO
log4j.logger.de.creditreform.crefoteam.ctcbase.sftputil.sftpconnection.SftpConnectionImpl=ERROR

# 4. Additivity (Verhindert doppeltes Loggen in Konsole UND Datei)
log4j.additivity.org.apache.commons.httpclient.HttpClient=false
log4j.additivity.de.creditreform.crefoteam=false
log4j.additivity.de.creditreform.crefoteam.ctcbase.sftputil.sftpconnection.SftpConnectionImpl=false
