DEFAULT.XML_STREAM_PROCESSOR=RECURSIVE
ENE-ABF-Crefos\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\ABF
ENE-ABF-Crefos\ zählen.CREFO_TAGNAME = crefonummer
ENE-ABF-Crefos\ zählen.INVERT_RESULTS = false
ENE-ABF-Crefos\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-ABF-Crefos\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-ABF-Crefos\ zählen.SEARCH1 = crefonummer=.*
ENE-ABF-Löschsätze\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\ABF
ENE-ABF-Löschsätze\ zählen.CREFO_TAGNAME = abf-loeschsatz-export
ENE-ABF-Löschsätze\ zählen.INVERT_RESULTS = false
ENE-ABF-Löschsätze\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-ABF-Löschsätze\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-ABF-Löschsätze\ zählen.SEARCH1 = crefonummer=.*
ENE-BDR-Crefos\ zählen.XML_STREAM_PROCESSOR=LINEAR
ENE-BDR-Crefos\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\BDR
ENE-BDR-Crefos\ zählen.CREFO_TAGNAME = crefonummer
ENE-BDR-Crefos\ zählen.INVERT_RESULTS = false
ENE-BDR-Crefos\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-BDR-Crefos\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-BDR-Crefos\ zählen.SEARCH1 = crefonummer=.*
ENE-BDR-Löschsätze\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\BDR
ENE-BDR-Löschsätze\ zählen.CREFO_TAGNAME = crefonummer
ENE-BDR-Löschsätze\ zählen.INVERT_RESULTS = false
ENE-BDR-Löschsätze\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-BDR-Löschsätze\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-BDR-Löschsätze\ zählen.SEARCH1 = crefonummer=.*
ENE-CTC-Crefos\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\CTC
ENE-CTC-Crefos\ zählen.CREFO_TAGNAME = crefonummer
ENE-CTC-Crefos\ zählen.INVERT_RESULTS = false
ENE-CTC-Crefos\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-CTC-Crefos\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-CTC-Crefos\ zählen.SEARCH1 = crefonummer=.*
ENE-CTC-Löschsätze\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\CTC
ENE-CTC-Löschsätze\ zählen.CREFO_TAGNAME = crefonummer
ENE-CTC-Löschsätze\ zählen.INVERT_RESULTS = false
ENE-CTC-Löschsätze\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-CTC-Löschsätze\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-CTC-Löschsätze\ zählen.SEARCH1 = crefonummer=.*
ENE-DRD-Crefos\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\DRD
ENE-DRD-Crefos\ zählen.CREFO_TAGNAME = crefonummer
ENE-DRD-Crefos\ zählen.INVERT_RESULTS = false
ENE-DRD-Crefos\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-DRD-Crefos\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-DRD-Crefos\ zählen.SEARCH1 = crefonummer=.*
ENE-DRD-Löschsätze\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\DRD
ENE-DRD-Löschsätze\ zählen.CREFO_TAGNAME = crefonummer
ENE-DRD-Löschsätze\ zählen.INVERT_RESULTS = false
ENE-DRD-Löschsätze\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-DRD-Löschsätze\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-DRD-Löschsätze\ zählen.SEARCH1 = crefonummer=.*
ENE-FSU-Crefos\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\FSU
ENE-FSU-Crefos\ zählen.CREFO_TAGNAME = crefonummer
ENE-FSU-Crefos\ zählen.INVERT_RESULTS = false
ENE-FSU-Crefos\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-FSU-Crefos\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-FSU-Crefos\ zählen.SEARCH1 = crefonummer=.*
ENE-FSU-Löschsätze\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\FSU
ENE-FSU-Löschsätze\ zählen.CREFO_TAGNAME = fsu-crefonummer
ENE-FSU-Löschsätze\ zählen.INVERT_RESULTS = false
ENE-FSU-Löschsätze\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-FSU-Löschsätze\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-FSU-Löschsätze\ zählen.SEARCH1 = fsu-crefonummer=.*
ENE-FVD-Crefos\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\FVD
ENE-FVD-Crefos\ zählen.CREFO_TAGNAME = crefonummer
ENE-FVD-Crefos\ zählen.INVERT_RESULTS = false
ENE-FVD-Crefos\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-FVD-Crefos\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-FVD-Crefos\ zählen.SEARCH1 = crefonummer=.*
ENE-FVD-Löschsätze\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\FVD
ENE-FVD-Löschsätze\ zählen.CREFO_TAGNAME = crefonummer
ENE-FVD-Löschsätze\ zählen.INVERT_RESULTS = false
ENE-FVD-Löschsätze\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-FVD-Löschsätze\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-FVD-Löschsätze\ zählen.SEARCH1 = crefonummer=.*
ENE-GDL-Crefos\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\GDL
ENE-GDL-Crefos\ zählen.CREFO_TAGNAME = company-identifier
ENE-GDL-Crefos\ zählen.INVERT_RESULTS = false
ENE-GDL-Crefos\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-GDL-Crefos\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-GDL-Crefos\ zählen.SEARCH1 = company-identifier=.*
ENE-GDL-Löschsätze\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\GDL
ENE-GDL-Löschsätze\ zählen.CREFO_TAGNAME = company-identifier
ENE-GDL-Löschsätze\ zählen.INVERT_RESULTS = false
ENE-GDL-Löschsätze\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-GDL-Löschsätze\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-GDL-Löschsätze\ zählen.SEARCH1 = company-identifier=.*
ENE-IKA-Crefos\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\IKA
ENE-IKA-Crefos\ zählen.CREFO_TAGNAME = Crefonummer
ENE-IKA-Crefos\ zählen.INVERT_RESULTS = false
ENE-IKA-Crefos\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-IKA-Crefos\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-IKA-Crefos\ zählen.SEARCH1 = Crefonummer=.*
ENE-IKA-Löschsätze\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\IKA
ENE-IKA-Löschsätze\ zählen.CREFO_TAGNAME = Crefonummer
ENE-IKA-Löschsätze\ zählen.INVERT_RESULTS = false
ENE-IKA-Löschsätze\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-IKA-Löschsätze\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-IKA-Löschsätze\ zählen.SEARCH1 = Crefonummer=.*
ENE-ISM-Crefos\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\ISM
ENE-ISM-Crefos\ zählen.CREFO_TAGNAME = crefo-number
ENE-ISM-Crefos\ zählen.INVERT_RESULTS = false
ENE-ISM-Crefos\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-ISM-Crefos\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-ISM-Crefos\ zählen.SEARCH1 = crefo-number=.*
ENE-ISM-Löschsätze\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\ISM
ENE-ISM-Löschsätze\ zählen.CREFO_TAGNAME = crefo-number
ENE-ISM-Löschsätze\ zählen.INVERT_RESULTS = false
ENE-ISM-Löschsätze\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-ISM-Löschsätze\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-ISM-Löschsätze\ zählen.SEARCH1 = crefo-number=.*
ENE-MIC-Beteiligte\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\MIC
ENE-MIC-Beteiligte\ zählen.CREFO_TAGNAME = crefonummer
ENE-MIC-Beteiligte\ zählen.INVERT_RESULTS = false
ENE-MIC-Beteiligte\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-MIC-Beteiligte\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-MIC-Beteiligte\ zählen.SEARCH1 = mic-beteiligte-person=.*
ENE-MIC-Crefos\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\MIC
ENE-MIC-Crefos\ zählen.CREFO_TAGNAME = crefonummer
ENE-MIC-Crefos\ zählen.INVERT_RESULTS = false
ENE-MIC-Crefos\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-MIC-Crefos\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-MIC-Crefos\ zählen.SEARCH1 = crefonummer=.*
ENE-MIC-Löschsätze\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\MIC
ENE-MIC-Löschsätze\ zählen.CREFO_TAGNAME = crefonummer
ENE-MIC-Löschsätze\ zählen.INVERT_RESULTS = false
ENE-MIC-Löschsätze\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-MIC-Löschsätze\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-MIC-Löschsätze\ zählen.SEARCH1 = crefonummer=.*
ENE-MIP-Crefos\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\MIP
ENE-MIP-Crefos\ zählen.CREFO_TAGNAME = crefonummer
ENE-MIP-Crefos\ zählen.INVERT_RESULTS = false
ENE-MIP-Crefos\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-MIP-Crefos\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-MIP-Crefos\ zählen.SEARCH1 = crefonummer=.*
ENE-MIP-Löschsätze\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\MIP
ENE-MIP-Löschsätze\ zählen.CREFO_TAGNAME = crefonummer
ENE-MIP-Löschsätze\ zählen.INVERT_RESULTS = false
ENE-MIP-Löschsätze\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-MIP-Löschsätze\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-MIP-Löschsätze\ zählen.SEARCH1 = crefonummer=.*
ENE-NIM-Crefos\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\NIM
ENE-NIM-Crefos\ zählen.CREFO_TAGNAME = crefonummer
ENE-NIM-Crefos\ zählen.INVERT_RESULTS = false
ENE-NIM-Crefos\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-NIM-Crefos\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-NIM-Crefos\ zählen.SEARCH1 = crefonummer=.*
ENE-NIM-Löschsätze\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\NIM
ENE-NIM-Löschsätze\ zählen.CREFO_TAGNAME = crefonummer
ENE-NIM-Löschsätze\ zählen.INVERT_RESULTS = false
ENE-NIM-Löschsätze\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-NIM-Löschsätze\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-NIM-Löschsätze\ zählen.SEARCH1 = crefonummer=.*
ENE-RTN-Crefos\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\RTN
ENE-RTN-Crefos\ zählen.CREFO_TAGNAME = crefonummer
ENE-RTN-Crefos\ zählen.INVERT_RESULTS = false
ENE-RTN-Crefos\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-RTN-Crefos\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-RTN-Crefos\ zählen.SEARCH1 = crefonummer=.*
ENE-RTN-Löschsätze\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\RTN
ENE-RTN-Löschsätze\ zählen.CREFO_TAGNAME = crefonummer
ENE-RTN-Löschsätze\ zählen.INVERT_RESULTS = false
ENE-RTN-Löschsätze\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-RTN-Löschsätze\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-RTN-Löschsätze\ zählen.SEARCH1 = crefonummer=.*
ENE-VSD-Crefos\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\VSD
ENE-VSD-Crefos\ zählen.CREFO_TAGNAME = crefonummer
ENE-VSD-Crefos\ zählen.INVERT_RESULTS = false
ENE-VSD-Crefos\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-VSD-Crefos\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-VSD-Crefos\ zählen.SEARCH1 = crefonummer=.*
ENE-VSD-Löschsätze\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\VSD
ENE-VSD-Löschsätze\ zählen.CREFO_TAGNAME = vsh-crefonummer
ENE-VSD-Löschsätze\ zählen.INVERT_RESULTS = false
ENE-VSD-Löschsätze\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-VSD-Löschsätze\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-VSD-Löschsätze\ zählen.SEARCH1 = vsh-crefonummer=.*
ENE-VSH-Crefos\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\VSH
ENE-VSH-Crefos\ zählen.CREFO_TAGNAME = crefonummer
ENE-VSH-Crefos\ zählen.INVERT_RESULTS = false
ENE-VSH-Crefos\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-VSH-Crefos\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-VSH-Crefos\ zählen.SEARCH1 = crefonummer=.*
ENE-VSH-Löschsätze\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\VSH
ENE-VSH-Löschsätze\ zählen.CREFO_TAGNAME = vsh-crefonummer
ENE-VSH-Löschsätze\ zählen.INVERT_RESULTS = false
ENE-VSH-Löschsätze\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-VSH-Löschsätze\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-VSH-Löschsätze\ zählen.SEARCH1 = vsh-crefonummer=.*
ENE-VSO-Crefos\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\VSO
ENE-VSO-Crefos\ zählen.CREFO_TAGNAME = crefonummer
ENE-VSO-Crefos\ zählen.INVERT_RESULTS = false
ENE-VSO-Crefos\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-VSO-Crefos\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-VSO-Crefos\ zählen.SEARCH1 = crefonummer=.*
ENE-VSO-Löschsätze\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\VSO
ENE-VSO-Löschsätze\ zählen.CREFO_TAGNAME = vsh-crefonummer
ENE-VSO-Löschsätze\ zählen.INVERT_RESULTS = false
ENE-VSO-Löschsätze\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-VSO-Löschsätze\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-VSO-Löschsätze\ zählen.SEARCH1 = vsh-crefonummer=.*
ENE-ZEW-Beteiligten\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\ZEW
ENE-ZEW-Beteiligten\ zählen.CREFO_TAGNAME = zew-beteiligten-daten
ENE-ZEW-Beteiligten\ zählen.INVERT_RESULTS = false
ENE-ZEW-Beteiligten\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-ZEW-Beteiligten\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-ZEW-Beteiligten\ zählen.SEARCH1 = crefonummer=.*
ENE-ZEW-Crefos\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\ZEW
ENE-ZEW-Crefos\ zählen.CREFO_TAGNAME = crefonummer
ENE-ZEW-Crefos\ zählen.INVERT_RESULTS = false
ENE-ZEW-Crefos\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-ZEW-Crefos\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-ZEW-Crefos\ zählen.SEARCH1 = crefonummer=.*
ENE-ZEW-Löschsätze\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\ZEW
ENE-ZEW-Löschsätze\ zählen.CREFO_TAGNAME = zew-crefonummer
ENE-ZEW-Löschsätze\ zählen.INVERT_RESULTS = false
ENE-ZEW-Löschsätze\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-ZEW-Löschsätze\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-ZEW-Löschsätze\ zählen.SEARCH1 = zew-crefonummer=.*
ENE-ZEW-Stammcrefos\ zählen.SOURCE = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\ZEW
ENE-ZEW-Stammcrefos\ zählen.CREFO_TAGNAME = zew-firmen-daten
ENE-ZEW-Stammcrefos\ zählen.INVERT_RESULTS = false
ENE-ZEW-Stammcrefos\ zählen.RESULTS_PATH = F:\\CTE-TestUtils\\Suche\\ENE\\ENE-Exports-Z\u00E4hlen\\Results
ENE-ZEW-Stammcrefos\ zählen.RESULT_TYPE = CREFOS_COUNT
ENE-ZEW-Stammcrefos\ zählen.SEARCH1 = crefonummer=.*
