ENE-CTC-Crefos\ zählen.SOURCE = C:\\Temp\\ENE\\CTC\\2018-09-13_14-31
ENE-CTC-Crefos\ zählen.CREFO_TAGNAME = crefonummer
ENE-CTC-Crefos\ zählen.INVERT_RESULTS = false
ENE-CTC-Crefos\ zählen.RESULTS_PATH = C:\\Temp\\ENE\\CTC
ENE-CTC-Crefos\ zählen.RESULT_TYPE = CREFOS_XML
ENE-CTC-Crefos\ zählen.SEARCH1 = crefonummer=.*
ENE-FSU-Analyse_Crefoss.SOURCE = C:\\Temp\\GEE_FSU
ENE-FSU-Analyse_Crefoss.CREFO_TAGNAME = crefonummer
ENE-FSU-Analyse_Crefoss.INVERT_RESULTS = false
ENE-FSU-Analyse_Crefoss.RESULTS_PATH = C:\\Temp\\GEE_FSU\\SearchResult
ENE-FSU-Analyse_Crefoss.RESULT_TYPE = CREFOS_XML
ENE-FSU-Analyse_Crefoss.SEARCH1 = crefonummer=.*
ENE-FSU-Analyse_Löschsätze.SOURCE = C:\\Temp\\GEE_FSU
ENE-FSU-Analyse_Löschsätze.CREFO_TAGNAME = fsu-crefonummer
ENE-FSU-Analyse_Löschsätze.INVERT_RESULTS = false
ENE-FSU-Analyse_Löschsätze.RESULTS_PATH = C:\\Temp\\GEE_FSU\\SearchResult
ENE-FSU-Analyse_Löschsätze.RESULT_TYPE = CREFOS_XML
ENE-FSU-Analyse_Löschsätze.SEARCH1 = nicht-mehr-aktuell=.*
ENE-FW-Crefos\ zählen.SOURCE = C:\\Temp\\ENE\\FW\\2018-09-13_14-31
ENE-FW-Crefos\ zählen.CREFO_TAGNAME = crefonummer
ENE-FW-Crefos\ zählen.INVERT_RESULTS = false
ENE-FW-Crefos\ zählen.RESULTS_PATH = C:\\Temp\\ENE\\FW
ENE-FW-Crefos\ zählen.RESULT_TYPE = CREFOS_XML
ENE-FW-Crefos\ zählen.SEARCH1 = crefonummer=.*
ENE-IKA-Crefos\ zählen.SOURCE = C:\\Temp\\ENE\\IKA\\2018-09-13_14-33
ENE-IKA-Crefos\ zählen.CREFO_TAGNAME = Crefonummer
ENE-IKA-Crefos\ zählen.INVERT_RESULTS = false
ENE-IKA-Crefos\ zählen.RESULTS_PATH = C:\\Temp\\ENE\\IKA\\Results
ENE-IKA-Crefos\ zählen.RESULT_TYPE = CREFOS_XML
ENE-IKA-Crefos\ zählen.SEARCH1 = Crefonummer=.*
ENE_NIM.SOURCE = E:\\Projekte\\CTE\\CTE.testsupport_client\\TestSupportGUI\\X-TESTS\\ENE\\2018-08-09_13-59
ENE_NIM.CREFO_TAGNAME = crefonummer
ENE_NIM.INVERT_RESULTS = false
ENE_NIM.RESULTS_PATH = E:\\Projekte\\CTE\\CTE.testsupport_client\\TestSupportGUI\\X-TESTS\\ENE\\2018-08-09_13-59/SearchResults
ENE_NIM.RESULT_TYPE = CREFOS_XML
ENE_NIM.SEARCH1 = angaben-liegen-vor-negativ-1=true
ENE_NIM.SEARCH2 = angaben-liegen-vor-negativ-2=true
ENE_NIM.SEARCH3 = angaben-liegen-vor-negativ-3=true
ENE_NIM.SEARCH4 = anschrift/ort=Minden
PRE-IKA-Crefos\ zählen.SOURCE = C:\\Temp\\PRE_IKA\\2018-08-20_09-15
PRE-IKA-Crefos\ zählen.CREFO_TAGNAME = Crefonummer
PRE-IKA-Crefos\ zählen.INVERT_RESULTS = false
PRE-IKA-Crefos\ zählen.RESULTS_PATH = C:\\Temp\\PRE_IKA\\Results
PRE-IKA-Crefos\ zählen.RESULT_TYPE = CREFOS_XML
PRE-IKA-Crefos\ zählen.SEARCH1 = Crefonummer=.*
PRE_IKAROS.SOURCE = C:\\Temp\\PRE_IKA
PRE_IKAROS.CREFO_TAGNAME = Crefonummer
PRE_IKAROS.INVERT_RESULTS = false
PRE_IKAROS.RESULTS_PATH = C:\\Temp\\PRE_IKA\\SearchResult
PRE_IKAROS.RESULT_TYPE = CREFOS_XML
PRE_IKAROS.SEARCH1 = Crefonummer=(6150227384|6150279211|2012673838|6150366328|2010849362|5230367992|2030384288)
PRE_IKAROS.SEARCH2 = Crefonummer=.*
PRE_VSH_705er\ Crefos.SOURCE = C:\\Temp\\PRE_VSH\\Mai
PRE_VSH_705er\ Crefos.CREFO_TAGNAME = crefonummer
PRE_VSH_705er\ Crefos.INVERT_RESULTS = false
PRE_VSH_705er\ Crefos.RESULTS_PATH = C:\\Temp\\PRE_VSH\\SearchResult
PRE_VSH_705er\ Crefos.RESULT_TYPE = CREFOS_XML
PRE_VSH_705er\ Crefos.SEARCH1 = crefonummer=(7050189652|8330491453|7050004668)
