db=oracle
jdbc.driver=oracle.jdbc.driver.OracleDriver
jdbc.url=jdbc:oracle:thin:@10.4.49.22:1521:ctcdb
#jdbc.url=jdbc:oracle:thin:@(DESCRIPTION=(ENABLE=BROKEN)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=ent-db-rac-scan.ecofis.de)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=cteene.creditreform.de)))
jdbc.username=ENE_ACTIVITI
jdbc.password=ene_activiti
