GEE\ -\ Sample.SOURCE = Y:\\acb\\export\\delta\\2016-05-18_13-55
GEE\ -\ Sample.CREFO_TAGNAME = crefonummer
GEE\ -\ Sample.INVERT_RESULTS = false
GEE\ -\ Sample.RESULTS_PATH = ./GEE/SearchResults
GEE\ -\ Sample.RESULT_TYPE = CREFOS_XML
GEE\ -\ Sample.SEARCH1 = Crefonummer=3390105291
