EH-Bilanzpositionen-2021-11-09_17-00.XML_STREAM_PROCESSOR = LINEAR
EH-Bilanzpositionen-2021-11-09_17-00.SOURCE = C:\\CTE\\Vergleich\\2021-11-09_17-00
EH-Bilanzpositionen-2021-11-09_17-00.CREFO_TAGNAME = crefonummer
EH-Bilanzpositionen-2021-11-09_17-00.LOGICAL_CONNECTION = LOGIC_OR
EH-Bilanzpositionen-2021-11-09_17-00.INVERT_RESULTS = false
EH-Bilanzpositionen-2021-11-09_17-00.RESULTS_PATH = C:\\CTE\\Vergleich\\Ergebnisse
EH-Bilanzpositionen-2021-11-09_17-00.RESULT_TYPE = CREFOS_XML
EH-Bilanzpositionen-2021-11-09_17-00.SEARCH1 = position-nr=990[0-1]
EH-Bilanzpositionen-2021-11-10_06-00.XML_STREAM_PROCESSOR = LINEAR
EH-Bilanzpositionen-2021-11-10_06-00.SOURCE = C:\\CTE\\Vergleich\\2021-11-10_06-00
EH-Bilanzpositionen-2021-11-10_06-00.CREFO_TAGNAME = crefonummer
EH-Bilanzpositionen-2021-11-10_06-00.LOGICAL_CONNECTION = LOGIC_OR
EH-Bilanzpositionen-2021-11-10_06-00.INVERT_RESULTS = false
EH-Bilanzpositionen-2021-11-10_06-00.RESULTS_PATH = C:\\CTE\\Vergleich\\Ergebnisse
EH-Bilanzpositionen-2021-11-10_06-00.RESULT_TYPE = CREFOS_XML
EH-Bilanzpositionen-2021-11-10_06-00.SEARCH1 = position-nr=990[0-1]
EH-Bilanzpositionen-2021-11-10_17-00.XML_STREAM_PROCESSOR = LINEAR
EH-Bilanzpositionen-2021-11-10_17-00.SOURCE = C:\\CTE\\Vergleich\\2021-11-10_17-00
EH-Bilanzpositionen-2021-11-10_17-00.CREFO_TAGNAME = crefonummer
EH-Bilanzpositionen-2021-11-10_17-00.LOGICAL_CONNECTION = LOGIC_OR
EH-Bilanzpositionen-2021-11-10_17-00.INVERT_RESULTS = false
EH-Bilanzpositionen-2021-11-10_17-00.RESULTS_PATH = C:\\CTE\\Vergleich\\Ergebnisse
EH-Bilanzpositionen-2021-11-10_17-00.RESULT_TYPE = CREFOS_XML
EH-Bilanzpositionen-2021-11-10_17-00.SEARCH1 = position-nr=990[0-1]
