Analyse.XML_STREAM_PROCESSOR = LINEAR
Analyse.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\PRE-EH
Analyse.CREFO_TAGNAME = crefonummer
Analyse.LOGICAL_CONNECTION = LOGIC_OR
Analyse.INVERT_RESULTS = false
Analyse.RESULT_TYPE = CREFOS_XML
Analyse.SEARCH1 = eh-loeschsatz-export=
CrefoListe.XML_STREAM_PROCESSOR = LINEAR
CrefoListe.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\PRE-EH
CrefoListe.CREFO_TAGNAME = crefonummer
CrefoListe.LOGICAL_CONNECTION = LOGIC_OR
CrefoListe.INVERT_RESULTS = false
CrefoListe.RESULT_TYPE = CREFOS_XML
CrefoListe.SEARCH1 = file::=CrefoListe.txt
