Suche\ 0.XML_STREAM_PROCESSOR = LINEAR
Suche\ 0.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH
Suche\ 0.CREFO_TAGNAME = crefonummer
Suche\ 0.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 0.INVERT_RESULTS = false
Suche\ 0.RESULT_TYPE = CREFOS_XML
Suche\ 0.SEARCH1 = eh-loeschsatz-export=
Suche\ 0.SEARCH2 = negativmerkmal=
Suche\ 0.SEARCH3 = crefonummer=9129045902
Suche\ 0_Clone.XML_STREAM_PROCESSOR = LINEAR
Suche\ 0_Clone.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH
Suche\ 0_Clone.CREFO_TAGNAME = crefonummer
Suche\ 0_Clone.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 0_Clone.INVERT_RESULTS = false
Suche\ 0_Clone.RESULT_TYPE = CREFOS_XML
Suche\ 0_Clone.SEARCH1 = eh-loeschsatz-export=
Suche\ 1.XML_STREAM_PROCESSOR = LINEAR
Suche\ 1.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-05_16-26
Suche\ 1.CREFO_TAGNAME = crefonummer
Suche\ 1.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 1.INVERT_RESULTS = false
Suche\ 1.RESULT_TYPE = CREFOS_XML
Suche\ 1.SEARCH1 = eh-loeschsatz-export=
Suche\ 10.XML_STREAM_PROCESSOR = LINEAR
Suche\ 10.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-10_17-53
Suche\ 10.CREFO_TAGNAME = crefonummer
Suche\ 10.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 10.INVERT_RESULTS = false
Suche\ 10.RESULT_TYPE = CREFOS_XML
Suche\ 10.SEARCH1 = eh-loeschsatz-export=
Suche\ 11.XML_STREAM_PROCESSOR = LINEAR
Suche\ 11.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-10_18-39
Suche\ 11.CREFO_TAGNAME = crefonummer
Suche\ 11.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 11.INVERT_RESULTS = false
Suche\ 11.RESULT_TYPE = CREFOS_XML
Suche\ 11.SEARCH1 = eh-loeschsatz-export=
Suche\ 12.XML_STREAM_PROCESSOR = LINEAR
Suche\ 12.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-17_20-11
Suche\ 12.CREFO_TAGNAME = crefonummer
Suche\ 12.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 12.INVERT_RESULTS = false
Suche\ 12.RESULT_TYPE = CREFOS_XML
Suche\ 12.SEARCH1 = eh-loeschsatz-export=
Suche\ 13.XML_STREAM_PROCESSOR = LINEAR
Suche\ 13.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-18_11-03
Suche\ 13.CREFO_TAGNAME = crefonummer
Suche\ 13.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 13.INVERT_RESULTS = false
Suche\ 13.RESULT_TYPE = CREFOS_XML
Suche\ 13.SEARCH1 = eh-loeschsatz-export=
Suche\ 13.SEARCH2 = register-aufnahme=2022-01-15+01:00
Suche\ 14.XML_STREAM_PROCESSOR = LINEAR
Suche\ 14.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-18_11-29
Suche\ 14.CREFO_TAGNAME = crefonummer
Suche\ 14.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 14.INVERT_RESULTS = false
Suche\ 14.RESULT_TYPE = CREFOS_XML
Suche\ 14.SEARCH1 = eh-loeschsatz-export=
Suche\ 14.SEARCH2 = negativmerkmal=
Suche\ 14.SEARCH3 = crefonummer=9129045902
Suche\ 15.XML_STREAM_PROCESSOR = LINEAR
Suche\ 15.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-22_09-04
Suche\ 15.CREFO_TAGNAME = crefonummer
Suche\ 15.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 15.INVERT_RESULTS = false
Suche\ 15.RESULT_TYPE = CREFOS_XML
Suche\ 15.SEARCH1 = eh-loeschsatz-export=
Suche\ 16.XML_STREAM_PROCESSOR = LINEAR
Suche\ 16.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-22_09-38
Suche\ 16.CREFO_TAGNAME = crefonummer
Suche\ 16.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 16.INVERT_RESULTS = false
Suche\ 16.RESULT_TYPE = CREFOS_XML
Suche\ 16.SEARCH1 = eh-loeschsatz-export=
Suche\ 17.XML_STREAM_PROCESSOR = LINEAR
Suche\ 17.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-22_10-15
Suche\ 17.CREFO_TAGNAME = crefonummer
Suche\ 17.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 17.INVERT_RESULTS = false
Suche\ 17.RESULT_TYPE = CREFOS_XML
Suche\ 17.SEARCH1 = eh-loeschsatz-export=
Suche\ 18.XML_STREAM_PROCESSOR = LINEAR
Suche\ 18.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-22_10-39
Suche\ 18.CREFO_TAGNAME = crefonummer
Suche\ 18.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 18.INVERT_RESULTS = false
Suche\ 18.RESULT_TYPE = CREFOS_XML
Suche\ 18.SEARCH1 = eh-loeschsatz-export=
Suche\ 19.XML_STREAM_PROCESSOR = LINEAR
Suche\ 19.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-23_11-19
Suche\ 19.CREFO_TAGNAME = crefonummer
Suche\ 19.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 19.INVERT_RESULTS = false
Suche\ 19.RESULT_TYPE = CREFOS_XML
Suche\ 19.SEARCH1 = eh-loeschsatz-export=
Suche\ 2.XML_STREAM_PROCESSOR = LINEAR
Suche\ 2.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-05_17-20
Suche\ 2.CREFO_TAGNAME = crefonummer
Suche\ 2.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 2.INVERT_RESULTS = false
Suche\ 2.RESULT_TYPE = CREFOS_XML
Suche\ 2.SEARCH1 = eh-loeschsatz-export=
Suche\ 20.XML_STREAM_PROCESSOR = LINEAR
Suche\ 20.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-23_11-50
Suche\ 20.CREFO_TAGNAME = crefonummer
Suche\ 20.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 20.INVERT_RESULTS = false
Suche\ 20.RESULT_TYPE = CREFOS_XML
Suche\ 20.SEARCH1 = eh-loeschsatz-export=
Suche\ 21.XML_STREAM_PROCESSOR = LINEAR
Suche\ 21.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-23_16-52
Suche\ 21.CREFO_TAGNAME = crefonummer
Suche\ 21.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 21.INVERT_RESULTS = false
Suche\ 21.RESULT_TYPE = CREFOS_XML
Suche\ 21.SEARCH1 = eh-loeschsatz-export=
Suche\ 22.XML_STREAM_PROCESSOR = LINEAR
Suche\ 22.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-23_17-20
Suche\ 22.CREFO_TAGNAME = crefonummer
Suche\ 22.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 22.INVERT_RESULTS = false
Suche\ 22.RESULT_TYPE = CREFOS_XML
Suche\ 22.SEARCH1 = eh-loeschsatz-export=
Suche\ 23.XML_STREAM_PROCESSOR = LINEAR
Suche\ 23.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-24_14-34
Suche\ 23.CREFO_TAGNAME = crefonummer
Suche\ 23.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 23.INVERT_RESULTS = false
Suche\ 23.RESULT_TYPE = CREFOS_XML
Suche\ 23.SEARCH1 = eh-loeschsatz-export=
Suche\ 24.XML_STREAM_PROCESSOR = LINEAR
Suche\ 24.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-24_15-05
Suche\ 24.CREFO_TAGNAME = crefonummer
Suche\ 24.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 24.INVERT_RESULTS = false
Suche\ 24.RESULT_TYPE = CREFOS_XML
Suche\ 24.SEARCH1 = eh-loeschsatz-export=
Suche\ 25.XML_STREAM_PROCESSOR = LINEAR
Suche\ 25.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-25_09-12
Suche\ 25.CREFO_TAGNAME = crefonummer
Suche\ 25.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 25.INVERT_RESULTS = false
Suche\ 25.RESULT_TYPE = CREFOS_XML
Suche\ 25.SEARCH1 = eh-loeschsatz-export=
Suche\ 26.XML_STREAM_PROCESSOR = LINEAR
Suche\ 26.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-25_09-45
Suche\ 26.CREFO_TAGNAME = crefonummer
Suche\ 26.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 26.INVERT_RESULTS = false
Suche\ 26.RESULT_TYPE = CREFOS_XML
Suche\ 26.SEARCH1 = eh-loeschsatz-export=
Suche\ 3.XML_STREAM_PROCESSOR = LINEAR
Suche\ 3.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-05_18-15
Suche\ 3.CREFO_TAGNAME = crefonummer
Suche\ 3.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 3.INVERT_RESULTS = false
Suche\ 3.RESULT_TYPE = CREFOS_XML
Suche\ 3.SEARCH1 = eh-loeschsatz-export=
Suche\ 4.XML_STREAM_PROCESSOR = LINEAR
Suche\ 4.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-09_09-26
Suche\ 4.CREFO_TAGNAME = crefonummer
Suche\ 4.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 4.INVERT_RESULTS = false
Suche\ 4.RESULT_TYPE = CREFOS_XML
Suche\ 4.SEARCH1 = eh-loeschsatz-export=
Suche\ 5.XML_STREAM_PROCESSOR = LINEAR
Suche\ 5.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-09_09-57
Suche\ 5.CREFO_TAGNAME = crefonummer
Suche\ 5.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 5.INVERT_RESULTS = false
Suche\ 5.RESULT_TYPE = CREFOS_XML
Suche\ 5.SEARCH1 = eh-loeschsatz-export=
Suche\ 6.XML_STREAM_PROCESSOR = LINEAR
Suche\ 6.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-09_16-53
Suche\ 6.CREFO_TAGNAME = crefonummer
Suche\ 6.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 6.INVERT_RESULTS = false
Suche\ 6.RESULT_TYPE = CREFOS_XML
Suche\ 6.SEARCH1 = eh-loeschsatz-export=
Suche\ 7.XML_STREAM_PROCESSOR = LINEAR
Suche\ 7.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-09_17-24
Suche\ 7.CREFO_TAGNAME = crefonummer
Suche\ 7.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 7.INVERT_RESULTS = false
Suche\ 7.RESULT_TYPE = CREFOS_XML
Suche\ 7.SEARCH1 = eh-loeschsatz-export=
Suche\ 8.XML_STREAM_PROCESSOR = LINEAR
Suche\ 8.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-10_08-31
Suche\ 8.CREFO_TAGNAME = crefonummer
Suche\ 8.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 8.INVERT_RESULTS = false
Suche\ 8.RESULT_TYPE = CREFOS_XML
Suche\ 8.SEARCH1 = eh-loeschsatz-export=
Suche\ 9.XML_STREAM_PROCESSOR = LINEAR
Suche\ 9.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH\\2024-01-10_09-03
Suche\ 9.CREFO_TAGNAME = crefonummer
Suche\ 9.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 9.INVERT_RESULTS = false
Suche\ 9.RESULT_TYPE = CREFOS_XML
Suche\ 9.SEARCH1 = eh-loeschsatz-export=
