Löschsätze.XML_STREAM_PROCESSOR = LINEAR
Löschsätze.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH
Löschsätze.CREFO_TAGNAME = crefonummer
Löschsätze.LOGICAL_CONNECTION = LOGIC_OR
Löschsätze.INVERT_RESULTS = false
Löschsätze.RESULT_TYPE = CREFOS_XML
Löschsätze.SEARCH1 = eh-loeschsatz-export=
Löschsätze&Negativmerkmale.XML_STREAM_PROCESSOR = LINEAR
Löschsätze&Negativmerkmale.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH
Löschsätze&Negativmerkmale.CREFO_TAGNAME = crefonummer
Löschsätze&Negativmerkmale.LOGICAL_CONNECTION = LOGIC_OR
Löschsätze&Negativmerkmale.INVERT_RESULTS = false
Löschsätze&Negativmerkmale.RESULT_TYPE = CREFOS_XML
Löschsätze&Negativmerkmale.SEARCH1 = eh-loeschsatz-export=
Löschsätze&Negativmerkmale.SEARCH2 = negativmerkmal=
