Suche\ 0.XML_STREAM_PROCESSOR = LINEAR
Suche\ 0.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH
Suche\ 0.CREFO_TAGNAME = crefonummer
Suche\ 0.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 0.INVERT_RESULTS = false
Suche\ 0.RESULT_TYPE = CREFOS_XML
Suche\ 0.SEARCH1 = eh-loeschsatz-export=
Suche\ 0.SEARCH2 = negativmerkmal=
Suche\ 0.SEARCH3 = crefonummer=9129045902
Suche\ 0_Clone.XML_STREAM_PROCESSOR = LINEAR
Suche\ 0_Clone.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\EH
Suche\ 0_Clone.CREFO_TAGNAME = crefonummer
Suche\ 0_Clone.LOGICAL_CONNECTION = LOGIC_OR
Suche\ 0_Clone.INVERT_RESULTS = false
Suche\ 0_Clone.RESULT_TYPE = CREFOS_XML
Suche\ 0_Clone.SEARCH1 = eh-loeschsatz-export=
