CrefoListe.XML_STREAM_PROCESSOR = LINEAR
CrefoListe.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\PRE-EH
CrefoListe.CREFO_TAGNAME = crefonummer
CrefoListe.LOGICAL_CONNECTION = LOGIC_OR
CrefoListe.INVERT_RESULTS = false
CrefoListe.RESULT_TYPE = CREFOS_XML
CrefoListe.SEARCH1 = file::=Loeschsaetze.txt
Löschsätze.XML_STREAM_PROCESSOR = LINEAR
Löschsätze.SOURCE = E:\\Projekte\\CTE\\testsupport_client\\TestSupportGUI\\X-TESTS\\ExportSuche\\PRE-EH
Löschsätze.CREFO_TAGNAME = crefonummer
Löschsätze.LOGICAL_CONNECTION = LOGIC_OR
Löschsätze.INVERT_RESULTS = false
Löschsätze.RESULT_TYPE = CREFOS_XML
Löschsätze.SEARCH1 = eh-loeschsatz-export=
