Hinfällige\ NM's.XML_STREAM_PROCESSOR = LINEAR
Hinfällige\ NM's.SOURCE = C:\\Temp\\2021-11-08_11-03
Hinfällige\ NM's.CREFO_TAGNAME = crefonummer
Hinfällige\ NM's.LOGICAL_CONNECTION = LOGIC_OR
Hinfällige\ NM's.INVERT_RESULTS = false
Hinfällige\ NM's.RESULTS_PATH = C:\\Temp\\2021-11-08_11-03
Hinfällige\ NM's.RESULT_TYPE = CREFOS_XML
Hinfällige\ NM's.SEARCH1 = status=HINFAELLIG
Hinfällige\ NM's.SEARCH2 = status=GUELTIG
Hinfällige\ NM's\ 2.XML_STREAM_PROCESSOR = LINEAR
Hinfällige\ NM's\ 2.SOURCE = C:\\Temp\\2021-11-08_12-12
Hinfällige\ NM's\ 2.CREFO_TAGNAME = crefonummer
Hinfällige\ NM's\ 2.LOGICAL_CONNECTION = LOGIC_OR
Hinfällige\ NM's\ 2.INVERT_RESULTS = false
Hinfällige\ NM's\ 2.RESULTS_PATH = C:\\Temp\\2021-11-08_12-12
Hinfällige\ NM's\ 2.RESULT_TYPE = CREFOS_XML
Hinfällige\ NM's\ 2.SEARCH1 = status=HINFAELLIG
Hinfällige\ NM's\ 2.SEARCH2 = status=GUELTIG
