Alle\ Exporte\ Full.XML_STREAM_PROCESSOR = LINEAR
Alle\ Exporte\ Full.SOURCE = SOURCE wurde nicht gesetzt!
Alle\ Exporte\ Full.CREFO_TAGNAME = crefonummer
Alle\ Exporte\ Full.LOGICAL_CONNECTION = LOGIC_OR
Alle\ Exporte\ Full.INVERT_RESULTS = false
Alle\ Exporte\ Full.RESULT_TYPE = CREFOS_LIST
Alle\ Exporte\ Full.SEARCH1 = inso-meldung=
Alle\ Exporte\ Full_X.XML_STREAM_PROCESSOR = LINEAR
Alle\ Exporte\ Full_X.SOURCE = SOURCE wurde nicht gesetzt!
Alle\ Exporte\ Full_X.CREFO_TAGNAME = crefonummer
Alle\ Exporte\ Full_X.LOGICAL_CONNECTION = LOGIC_OR
Alle\ Exporte\ Full_X.INVERT_RESULTS = false
Alle\ Exporte\ Full_X.RESULT_TYPE = CREFOS_LIST
Alle\ Exporte\ Full_X.SEARCH1 = inso-meldung=
Alle\ Exporte\ Monthly.XML_STREAM_PROCESSOR = LINEAR
Alle\ Exporte\ Monthly.SOURCE = SOURCE wurde nicht gesetzt!
Alle\ Exporte\ Monthly.CREFO_TAGNAME = crefonummer
Alle\ Exporte\ Monthly.LOGICAL_CONNECTION = LOGIC_OR
Alle\ Exporte\ Monthly.INVERT_RESULTS = false
Alle\ Exporte\ Monthly.RESULT_TYPE = CREFOS_LIST
Alle\ Exporte\ Monthly.SEARCH1 = inso-meldung=
